lidar_continuous_num: 5
YAML: 1.0
rtk_pos_noise: 2.0
origin:
  - 276727.9669506345
  - 4685962.446515145
  - 272.504
rtk_height_noise_ratio: 10.0
preprocess:
  lidar_type: 2
  scan_line: 32
  time_scale: 1e-3
rtk_ext:
  t: [0, 0.24, -0.283]
lio_yaml: ./config/velodyne_nclt.yaml
bag_path: /workspace_18_04/slam_in_autonomous_driving/dataset/sad/nclt/20120429.bag
common:
  imu_topic: imu_raw
  dataset: nclt
  lid_topic: points_raw
  time_sync_en: false
loop_closing:
  skip_id: 5
  ndt_score_th: 4.5
  min_id_interval: 100
  min_distance: 30
rtk_ang_noise: 5.0
rtk_has_rot: false
map_data: ./data/ch9/map_data/
rtk_outlier_th: 1.0
mapping:
  extrinsic_T: [0, 0, 0.28]
  extrinsic_est_en: true
  extrinsic_R: [1, 0, 0, 0, 1, 0, 0, 0, 1]
max_iteration: 10
imu_has_gravity: true
point_filter_num: 3