rtk_outlier_th: 1.0
mapping:
  extrinsic_T: [0, 0, 0.28]
  extrinsic_R: [1, 0, 0, 0, 1, 0, 0, 0, 1]
  extrinsic_est_en: true
rtk_has_rot: false
imu_has_gravity: true
rtk_ang_noise: 5.0
preprocess:
  time_scale: 1e-3
  scan_line: 32
  lidar_type: 2
origin:
  - 276727.9669506345
  - 4685962.446515145
  - 272.504
common:
  imu_topic: imu_raw
  time_sync_en: false
  dataset: nclt
  lid_topic: points_raw
rtk_height_noise_ratio: 10.0
YAML: 1.0
loop_closing:
  min_distance: 30
  skip_id: 5
  min_id_interval: 100
  ndt_score_th: 4.5
rtk_pos_noise: 2.0
rtk_ext:
  t: [0, 0.24, -0.283]
bag_path: /workspace_18_04/slam_in_autonomous_driving/dataset/sad/nclt/20120429.bag
lidar_continuous_num: 5
max_iteration: 10
map_data: ./data/ch9/map_data/
point_filter_num: 3
lio_yaml: ./config/velodyne_nclt.yaml